/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 43e7bfc1df31
 */

import { analyzeAiVisionModeration } from "../../funcs/analyzeAiVisionModeration.js";
import { AnalyzeAIVisionModerationRequest$zodSchema } from "../../models/analyzeaivisionmoderationrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AnalyzeAIVisionModerationRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeAiVisionModeration: ToolDefinition<typeof args> = {
  name: "analyze-ai-vision-moderation",
  description: `Analyze - AI Vision Moderation

The Moderation mode accepts multiple questions about an image, to which the response provides concise answers of "yes," "no," or "unknown." This functionality allows for a nuanced evaluation of whether the image adheres to specific content policies, creative specs, or aesthetic criteria.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeAiVisionModeration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
