/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07290045f952
 */

import { analyzeGoogleTagging } from "../../funcs/analyzeGoogleTagging.js";
import { BaseAnalyzeRequest$zodSchema } from "../../models/baseanalyzerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BaseAnalyzeRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeGoogleTagging: ToolDefinition<typeof args> = {
  name: "analyze-google-tagging",
  description: `Analyze - Google Tagging

Provides tags for an image using Google's tagging service.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeGoogleTagging(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
