/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d69769811e99
 */

import { analyzeAiVisionGeneral } from "../../funcs/analyzeAiVisionGeneral.js";
import { AnalyzeAIVisionGeneralRequest$zodSchema } from "../../models/analyzeaivisiongeneralrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AnalyzeAIVisionGeneralRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeAiVisionGeneral: ToolDefinition<typeof args> = {
  name: "analyze-ai-vision-general",
  description: `Analyze - AI Vision General

The General mode serves a wide array of applications by providing detailed answers to diverse questions about an image. Users can inquire about any aspect of an image, such as identifying objects, understanding scenes, or interpreting text within the image.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeAiVisionGeneral(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
