/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e0306d3db7bf
 */

import { analyzeGoogleLogoDetection } from "../../funcs/analyzeGoogleLogoDetection.js";
import { BaseAnalyzeRequest$zodSchema } from "../../models/baseanalyzerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BaseAnalyzeRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeGoogleLogoDetection: ToolDefinition<typeof args> = {
  name: "analyze-google-logo-detection",
  description: `Analyze - Google Logo Detection

Detects popular product logos within an image.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeGoogleLogoDetection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
