/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e84490166b98
 */

import { analyzeHumanAnatomy } from "../../funcs/analyzeHumanAnatomy.js";
import { BaseAnalyzeRequest$zodSchema } from "../../models/baseanalyzerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BaseAnalyzeRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeHumanAnatomy: ToolDefinition<typeof args> = {
  name: "analyze-human-anatomy",
  description: `Analyze - Human Anatomy

Analyze an image using the [Human Anatomy](https://cloudinary.com/documentation/cloudinary_ai_content_analysis_addon#ai_based_image_captioning) content-aware detection model. Cloudinary's human anatomy model identifies parts of the human body in an image. It works best when the majority of a human body is detected in the image.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeHumanAnatomy(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
