/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5690b2c184a3
 */

import { analyzeShopClassifier } from "../../funcs/analyzeShopClassifier.js";
import { BaseAnalyzeRequest$zodSchema } from "../../models/baseanalyzerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BaseAnalyzeRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeShopClassifier: ToolDefinition<typeof args> = {
  name: "analyze-shop-classifier",
  description: `Analyze - Shop Classifier

Analyze an image using the [Shop Classifier](https://cloudinary.com/documentation/cloudinary_ai_content_analysis_addon#ai_based_image_captioning) content-aware detection model. Cloudinary's shop classifier model detects if the image is a product image taken in a studio, or if it's a natural image.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeShopClassifier(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
