/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e79d6f5e602f
 */

import { analyzeCaptioning } from "../../funcs/analyzeCaptioning.js";
import { BaseAnalyzeRequest$zodSchema } from "../../models/baseanalyzerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BaseAnalyzeRequest$zodSchema.describe(
    `A JSON object containing request parameters`,
  ),
};

export const tool$analyzeCaptioning: ToolDefinition<typeof args> = {
  name: "analyze-captioning",
  description: `Analyze - Captioning

Provides a caption for an image.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await analyzeCaptioning(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
