/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eddba7bb471c
 */

import * as z from "zod";
import { tasksGetStatus } from "../../funcs/tasksGetStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  task_id: z.string().describe("The ID of the analysis task"),
};

export const tool$tasksGetStatus: ToolDefinition<typeof args> = {
  name: "tasks-get-status",
  description: `Get analysis task status

Get the status of an analysis task.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetStatus(
      client,
      args.task_id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
