/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a709b8ce2ddb
 */

/**
 * Available scopes for the OAuth2 OAuth 2.0 scheme (authorizationCode flow).
 */
export type OAuth2Scope =
  /**
   * Analyze media
   */
  | "media_analysis"
  /**
   * Query status of analysis tasks
   */
  | "query_analysis_tasks";
