/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 73133ffc6631
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const Value = {
  Yes: "yes",
  No: "no",
  Unknown: "unknown",
} as const;
export type Value = ClosedEnum<typeof Value>;

export const Value$zodSchema = z.enum([
  "yes",
  "no",
  "unknown",
]);

export type AIVisionModerationAnalysisDataResponse = {
  prompt?: string | undefined;
  value?: Value | undefined;
};

export const AIVisionModerationAnalysisDataResponse$zodSchema: z.ZodType<
  AIVisionModerationAnalysisDataResponse
> = z.object({
  prompt: z.string().optional(),
  value: Value$zodSchema.optional(),
});

export type AIVisionModerationAnalysisData = {
  responses: Array<AIVisionModerationAnalysisDataResponse>;
  model_version?: number | undefined;
};

export const AIVisionModerationAnalysisData$zodSchema: z.ZodType<
  AIVisionModerationAnalysisData
> = z.object({
  model_version: z.int().optional(),
  responses: z.array(
    z.lazy(() => AIVisionModerationAnalysisDataResponse$zodSchema),
  ),
});
