/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 041ff63ac3f6
 */

import * as z from "zod";

export type Tag = { name?: string | undefined };

export const Tag$zodSchema: z.ZodType<Tag> = z.object({
  name: z.string().optional(),
});

export type AIVisionTaggingAnalysisData = {
  tags: Array<Tag>;
  model_version?: number | undefined;
};

export const AIVisionTaggingAnalysisData$zodSchema: z.ZodType<
  AIVisionTaggingAnalysisData
> = z.object({
  model_version: z.int().optional(),
  tags: z.array(z.lazy(() => Tag$zodSchema)),
});
