/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 885daeccfcb9
 */

import * as z from "zod";

export type AIVisionGeneralAnalysisDataResponse = {
  value?: string | undefined;
};

export const AIVisionGeneralAnalysisDataResponse$zodSchema: z.ZodType<
  AIVisionGeneralAnalysisDataResponse
> = z.object({
  value: z.string().optional(),
});

export type AIVisionGeneralAnalysisData = {
  responses: Array<AIVisionGeneralAnalysisDataResponse>;
  model_version?: number | undefined;
};

export const AIVisionGeneralAnalysisData$zodSchema: z.ZodType<
  AIVisionGeneralAnalysisData
> = z.object({
  model_version: z.int().optional(),
  responses: z.array(
    z.lazy(() => AIVisionGeneralAnalysisDataResponse$zodSchema),
  ),
});
