/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d3dfbd56135
 */

import * as z from "zod";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";
import {
  WatermarkDetectionAnalysisData,
  WatermarkDetectionAnalysisData$zodSchema,
} from "./watermarkdetectionanalysisdata.js";

export type AnalyzeWatermarkDetectionResponseData = {
  entity?: string | undefined;
  analysis?: WatermarkDetectionAnalysisData | undefined;
};

export const AnalyzeWatermarkDetectionResponseData$zodSchema: z.ZodType<
  AnalyzeWatermarkDetectionResponseData
> = z.object({
  analysis: WatermarkDetectionAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeWatermarkDetectionResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeWatermarkDetectionResponseData | undefined;
};

export const AnalyzeWatermarkDetectionResponse$zodSchema: z.ZodType<
  AnalyzeWatermarkDetectionResponse
> = z.object({
  data: z.lazy(() => AnalyzeWatermarkDetectionResponseData$zodSchema)
    .optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
