/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba10618ff49a
 */

import * as z from "zod";
import {
  CocoAnalysisData,
  CocoAnalysisData$zodSchema,
} from "./cocoanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeCocoResponseData = {
  entity?: string | undefined;
  analysis?: CocoAnalysisData | undefined;
};

export const AnalyzeCocoResponseData$zodSchema: z.ZodType<
  AnalyzeCocoResponseData
> = z.object({
  analysis: CocoAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeCocoResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeCocoResponseData | undefined;
};

export const AnalyzeCocoResponse$zodSchema: z.ZodType<AnalyzeCocoResponse> = z
  .object({
    data: z.lazy(() => AnalyzeCocoResponseData$zodSchema).optional(),
    limits: LimitsObject$zodSchema.nullable().optional(),
    request_id: z.string().optional(),
  });
