/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4590a235350e
 */

import * as z from "zod";
import {
  AnalyzeImageQualityResponse,
  AnalyzeImageQualityResponse$zodSchema,
} from "./analyzeimagequalityresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeImageQualityResponseResponse =
  | AnalyzeImageQualityResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeImageQualityResponseResponse$zodSchema: z.ZodType<
  AnalyzeImageQualityResponseResponse
> = z.union([
  AnalyzeImageQualityResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
