/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e8ba0f446043
 */

import * as z from "zod";
import { Source, Source$zodSchema } from "./source.js";

export type AnalyzeAIVisionGeneralRequest = {
  source: Source;
  async?: boolean | undefined;
  notification_url?: string | undefined;
  prompts?: Array<string> | undefined;
};

export const AnalyzeAIVisionGeneralRequest$zodSchema: z.ZodType<
  AnalyzeAIVisionGeneralRequest
> = z.object({
  async: z.boolean().optional().describe(
    "Whether to perform the analysis asynchronously.\nIf true, the response is returned immediately and analysis is done in the background.\nOnce complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.",
  ),
  notification_url: z.string().optional().describe(
    "The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.",
  ),
  prompts: z.array(z.string()).optional().describe(
    "One or more prompts of open questions or tasks with an open answer",
  ),
  source: Source$zodSchema,
});
