/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d8917054e34
 */

import * as z from "zod";
import {
  AnalyzeGoogleLogoDetectionResponse,
  AnalyzeGoogleLogoDetectionResponse$zodSchema,
} from "./analyzegooglelogodetectionresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeGoogleLogoDetectionResponseResponse =
  | AnalyzeGoogleLogoDetectionResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeGoogleLogoDetectionResponseResponse$zodSchema: z.ZodType<
  AnalyzeGoogleLogoDetectionResponseResponse
> = z.union([
  AnalyzeGoogleLogoDetectionResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
