/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37f00258b4df
 */

import * as z from "zod";
import { Source, Source$zodSchema } from "./source.js";

export type AnalyzeAIVisionModerationRequest = {
  source: Source;
  async?: boolean | undefined;
  notification_url?: string | undefined;
  rejection_questions?: Array<string> | undefined;
};

export const AnalyzeAIVisionModerationRequest$zodSchema: z.ZodType<
  AnalyzeAIVisionModerationRequest
> = z.object({
  async: z.boolean().optional().describe(
    "Whether to perform the analysis asynchronously.\nIf true, the response is returned immediately and analysis is done in the background.\nOnce complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.",
  ),
  notification_url: z.string().optional().describe(
    "The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.",
  ),
  rejection_questions: z.array(z.string()).optional().describe(
    "A list of yes/no questions",
  ),
  source: Source$zodSchema,
});
