/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 77e26c854bfa
 */

import * as z from "zod";
import {
  AnalyzeShopClassifierResponse,
  AnalyzeShopClassifierResponse$zodSchema,
} from "./analyzeshopclassifierresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeShopClassifierResponseResponse =
  | AnalyzeShopClassifierResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeShopClassifierResponseResponse$zodSchema: z.ZodType<
  AnalyzeShopClassifierResponseResponse
> = z.union([
  AnalyzeShopClassifierResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
