/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 584adef7fe82
 */

import * as z from "zod";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";
import {
  LvisAnalysisData,
  LvisAnalysisData$zodSchema,
} from "./lvisanalysisdata.js";

export type AnalyzeLvisResponseData = {
  entity?: string | undefined;
  analysis?: LvisAnalysisData | undefined;
};

export const AnalyzeLvisResponseData$zodSchema: z.ZodType<
  AnalyzeLvisResponseData
> = z.object({
  analysis: LvisAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeLvisResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeLvisResponseData | undefined;
};

export const AnalyzeLvisResponse$zodSchema: z.ZodType<AnalyzeLvisResponse> = z
  .object({
    data: z.lazy(() => AnalyzeLvisResponseData$zodSchema).optional(),
    limits: LimitsObject$zodSchema.nullable().optional(),
    request_id: z.string().optional(),
  });
