/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6f0632ec6a69
 */

import * as z from "zod";
import {
  AnalyzeAIVisionTaggingResponse,
  AnalyzeAIVisionTaggingResponse$zodSchema,
} from "./analyzeaivisiontaggingresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeAiVisionTaggingResponseResponse =
  | AnalyzeAIVisionTaggingResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeAiVisionTaggingResponseResponse$zodSchema: z.ZodType<
  AnalyzeAiVisionTaggingResponseResponse
> = z.union([
  AnalyzeAIVisionTaggingResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
