/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd968f2df382
 */

import * as z from "zod";
import {
  CaptioningAnalysisData,
  CaptioningAnalysisData$zodSchema,
} from "./captioninganalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeCaptioningResponseData = {
  entity?: string | undefined;
  analysis?: CaptioningAnalysisData | undefined;
};

export const AnalyzeCaptioningResponseData$zodSchema: z.ZodType<
  AnalyzeCaptioningResponseData
> = z.object({
  analysis: CaptioningAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeCaptioningResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeCaptioningResponseData | undefined;
};

export const AnalyzeCaptioningResponse$zodSchema: z.ZodType<
  AnalyzeCaptioningResponse
> = z.object({
  data: z.lazy(() => AnalyzeCaptioningResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
