/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 67f27471e0b8
 */

import * as z from "zod";
import {
  AnalyzeWatermarkDetectionResponse,
  AnalyzeWatermarkDetectionResponse$zodSchema,
} from "./analyzewatermarkdetectionresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeWatermarkDetectionResponseResponse =
  | AnalyzeWatermarkDetectionResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeWatermarkDetectionResponseResponse$zodSchema: z.ZodType<
  AnalyzeWatermarkDetectionResponseResponse
> = z.union([
  AnalyzeWatermarkDetectionResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
