/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6faae5b9fbee
 */

import * as z from "zod";
import {
  AIVisionTaggingAnalysisData,
  AIVisionTaggingAnalysisData$zodSchema,
} from "./aivisiontagginganalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeAIVisionTaggingResponseData = {
  entity?: string | undefined;
  analysis?: AIVisionTaggingAnalysisData | undefined;
};

export const AnalyzeAIVisionTaggingResponseData$zodSchema: z.ZodType<
  AnalyzeAIVisionTaggingResponseData
> = z.object({
  analysis: AIVisionTaggingAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeAIVisionTaggingResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeAIVisionTaggingResponseData | undefined;
};

export const AnalyzeAIVisionTaggingResponse$zodSchema: z.ZodType<
  AnalyzeAIVisionTaggingResponse
> = z.object({
  data: z.lazy(() => AnalyzeAIVisionTaggingResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
