/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 32957ce38bf8
 */

import * as z from "zod";
import { Source, Source$zodSchema } from "./source.js";

export type TagDefinition = { name: string; description: string };

export const TagDefinition$zodSchema: z.ZodType<TagDefinition> = z.object({
  description: z.string().describe(
    "A description to be used by the AI to determine whether the tag should be applied",
  ),
  name: z.string().describe(
    "The name of the tag to apply. This can be any string and does not affect the decision process",
  ),
});

export type AnalyzeAIVisionTaggingRequest = {
  source: Source;
  async?: boolean | undefined;
  notification_url?: string | undefined;
  tag_definitions: Array<TagDefinition>;
};

export const AnalyzeAIVisionTaggingRequest$zodSchema: z.ZodType<
  AnalyzeAIVisionTaggingRequest
> = z.object({
  async: z.boolean().optional().describe(
    "Whether to perform the analysis asynchronously.\nIf true, the response is returned immediately and analysis is done in the background.\nOnce complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.",
  ),
  notification_url: z.string().optional().describe(
    "The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.",
  ),
  source: Source$zodSchema,
  tag_definitions: z.array(z.lazy(() => TagDefinition$zodSchema)),
});
