/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d9ccacd49f1f
 */

import * as z from "zod";
import {
  AnalyzeCocoResponse,
  AnalyzeCocoResponse$zodSchema,
} from "./analyzecocoresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeCocoResponseResponse =
  | AnalyzeCocoResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeCocoResponseResponse$zodSchema: z.ZodType<
  AnalyzeCocoResponseResponse
> = z.union([
  AnalyzeCocoResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
