/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 45439484834e
 */

import * as z from "zod";
import {
  AIVisionModerationAnalysisData,
  AIVisionModerationAnalysisData$zodSchema,
} from "./aivisionmoderationanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeAIVisionModerationResponseData = {
  entity?: string | undefined;
  analysis?: AIVisionModerationAnalysisData | undefined;
};

export const AnalyzeAIVisionModerationResponseData$zodSchema: z.ZodType<
  AnalyzeAIVisionModerationResponseData
> = z.object({
  analysis: AIVisionModerationAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeAIVisionModerationResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeAIVisionModerationResponseData | undefined;
};

export const AnalyzeAIVisionModerationResponse$zodSchema: z.ZodType<
  AnalyzeAIVisionModerationResponse
> = z.object({
  data: z.lazy(() => AnalyzeAIVisionModerationResponseData$zodSchema)
    .optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
