/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9674ffd6588c
 */

import * as z from "zod";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";
import {
  UnidetAnalysisData,
  UnidetAnalysisData$zodSchema,
} from "./unidetanalysisdata.js";

export type AnalyzeUnidetResponseData = {
  entity?: string | undefined;
  analysis?: UnidetAnalysisData | undefined;
};

export const AnalyzeUnidetResponseData$zodSchema: z.ZodType<
  AnalyzeUnidetResponseData
> = z.object({
  analysis: UnidetAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeUnidetResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeUnidetResponseData | undefined;
};

export const AnalyzeUnidetResponse$zodSchema: z.ZodType<AnalyzeUnidetResponse> =
  z.object({
    data: z.lazy(() => AnalyzeUnidetResponseData$zodSchema).optional(),
    limits: LimitsObject$zodSchema.nullable().optional(),
    request_id: z.string().optional(),
  });
