/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dabb9d07e03c
 */

import * as z from "zod";
import {
  CldTextAnalysisData,
  CldTextAnalysisData$zodSchema,
} from "./cldtextanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeCldTextResponseData = {
  entity?: string | undefined;
  analysis?: CldTextAnalysisData | undefined;
};

export const AnalyzeCldTextResponseData$zodSchema: z.ZodType<
  AnalyzeCldTextResponseData
> = z.object({
  analysis: CldTextAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeCldTextResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeCldTextResponseData | undefined;
};

export const AnalyzeCldTextResponse$zodSchema: z.ZodType<
  AnalyzeCldTextResponse
> = z.object({
  data: z.lazy(() => AnalyzeCldTextResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
