/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3f7256aacb78
 */

import * as z from "zod";
import {
  AIVisionGeneralAnalysisData,
  AIVisionGeneralAnalysisData$zodSchema,
} from "./aivisiongeneralanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeAIVisionGeneralResponseData = {
  entity?: string | undefined;
  analysis?: AIVisionGeneralAnalysisData | undefined;
};

export const AnalyzeAIVisionGeneralResponseData$zodSchema: z.ZodType<
  AnalyzeAIVisionGeneralResponseData
> = z.object({
  analysis: AIVisionGeneralAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeAIVisionGeneralResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeAIVisionGeneralResponseData | undefined;
};

export const AnalyzeAIVisionGeneralResponse$zodSchema: z.ZodType<
  AnalyzeAIVisionGeneralResponse
> = z.object({
  data: z.lazy(() => AnalyzeAIVisionGeneralResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
