/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e274a62d3b4
 */

import * as z from "zod";
import {
  GoogleTaggingAnalysisData,
  GoogleTaggingAnalysisData$zodSchema,
} from "./googletagginganalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeGoogleTaggingResponseData = {
  entity?: string | undefined;
  analysis?: GoogleTaggingAnalysisData | undefined;
};

export const AnalyzeGoogleTaggingResponseData$zodSchema: z.ZodType<
  AnalyzeGoogleTaggingResponseData
> = z.object({
  analysis: GoogleTaggingAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeGoogleTaggingResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeGoogleTaggingResponseData | undefined;
};

export const AnalyzeGoogleTaggingResponse$zodSchema: z.ZodType<
  AnalyzeGoogleTaggingResponse
> = z.object({
  data: z.lazy(() => AnalyzeGoogleTaggingResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
