/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5fd0cf1db423
 */

import * as z from "zod";
import {
  AnalyzeCldTextResponse,
  AnalyzeCldTextResponse$zodSchema,
} from "./analyzecldtextresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeCldTextResponseResponse =
  | AnalyzeCldTextResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeCldTextResponseResponse$zodSchema: z.ZodType<
  AnalyzeCldTextResponseResponse
> = z.union([
  AnalyzeCldTextResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
