/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d1b5fd389d54
 */

import * as z from "zod";
import {
  AnalyzeUnidetResponse,
  AnalyzeUnidetResponse$zodSchema,
} from "./analyzeunidetresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeUnidetResponseResponse =
  | AnalyzeUnidetResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeUnidetResponseResponse$zodSchema: z.ZodType<
  AnalyzeUnidetResponseResponse
> = z.union([
  AnalyzeUnidetResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
