/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d5717f598877
 */

import * as z from "zod";
import {
  AnalyzeCaptioningResponse,
  AnalyzeCaptioningResponse$zodSchema,
} from "./analyzecaptioningresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeCaptioningResponseResponse =
  | AnalyzeCaptioningResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeCaptioningResponseResponse$zodSchema: z.ZodType<
  AnalyzeCaptioningResponseResponse
> = z.union([
  AnalyzeCaptioningResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
