/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f751f21011a2
 */

import * as z from "zod";
import {
  CldFashionAnalysisData,
  CldFashionAnalysisData$zodSchema,
} from "./cldfashionanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeCldFashionResponseData = {
  entity?: string | undefined;
  analysis?: CldFashionAnalysisData | undefined;
};

export const AnalyzeCldFashionResponseData$zodSchema: z.ZodType<
  AnalyzeCldFashionResponseData
> = z.object({
  analysis: CldFashionAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeCldFashionResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeCldFashionResponseData | undefined;
};

export const AnalyzeCldFashionResponse$zodSchema: z.ZodType<
  AnalyzeCldFashionResponse
> = z.object({
  data: z.lazy(() => AnalyzeCldFashionResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
