/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85a52261e728
 */

import * as z from "zod";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";
import {
  ShopClassifierAnalysisData,
  ShopClassifierAnalysisData$zodSchema,
} from "./shopclassifieranalysisdata.js";

export type AnalyzeShopClassifierResponseData = {
  entity?: string | undefined;
  analysis?: ShopClassifierAnalysisData | undefined;
};

export const AnalyzeShopClassifierResponseData$zodSchema: z.ZodType<
  AnalyzeShopClassifierResponseData
> = z.object({
  analysis: ShopClassifierAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeShopClassifierResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeShopClassifierResponseData | undefined;
};

export const AnalyzeShopClassifierResponse$zodSchema: z.ZodType<
  AnalyzeShopClassifierResponse
> = z.object({
  data: z.lazy(() => AnalyzeShopClassifierResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
