/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 68a0e01f801b
 */

import * as z from "zod";
import {
  AnalyzeLvisResponse,
  AnalyzeLvisResponse$zodSchema,
} from "./analyzelvisresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeLvisResponseResponse =
  | AnalyzeLvisResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeLvisResponseResponse$zodSchema: z.ZodType<
  AnalyzeLvisResponseResponse
> = z.union([
  AnalyzeLvisResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
