/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a078ef452dfa
 */

import * as z from "zod";
import {
  HumanAnatomyAnalysisData,
  HumanAnatomyAnalysisData$zodSchema,
} from "./humananatomyanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeHumanAnatomyResponseData = {
  entity?: string | undefined;
  analysis?: HumanAnatomyAnalysisData | undefined;
};

export const AnalyzeHumanAnatomyResponseData$zodSchema: z.ZodType<
  AnalyzeHumanAnatomyResponseData
> = z.object({
  analysis: HumanAnatomyAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeHumanAnatomyResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeHumanAnatomyResponseData | undefined;
};

export const AnalyzeHumanAnatomyResponse$zodSchema: z.ZodType<
  AnalyzeHumanAnatomyResponse
> = z.object({
  data: z.lazy(() => AnalyzeHumanAnatomyResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
