/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2492854e57ce
 */

import * as z from "zod";
import {
  AnalyzeGoogleTaggingResponse,
  AnalyzeGoogleTaggingResponse$zodSchema,
} from "./analyzegoogletaggingresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeGoogleTaggingResponseResponse =
  | AnalyzeGoogleTaggingResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeGoogleTaggingResponseResponse$zodSchema: z.ZodType<
  AnalyzeGoogleTaggingResponseResponse
> = z.union([
  AnalyzeGoogleTaggingResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
