/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 33e6f42893cc
 */

import * as z from "zod";
import {
  AnalyzeCldFashionResponse,
  AnalyzeCldFashionResponse$zodSchema,
} from "./analyzecldfashionresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeCldFashionResponseResponse =
  | AnalyzeCldFashionResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeCldFashionResponseResponse$zodSchema: z.ZodType<
  AnalyzeCldFashionResponseResponse
> = z.union([
  AnalyzeCldFashionResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
