/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 11a0be4b4171
 */

import * as z from "zod";
import {
  GoogleLogoDetectionAnalysisData,
  GoogleLogoDetectionAnalysisData$zodSchema,
} from "./googlelogodetectionanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeGoogleLogoDetectionResponseData = {
  entity?: string | undefined;
  analysis?: GoogleLogoDetectionAnalysisData | undefined;
};

export const AnalyzeGoogleLogoDetectionResponseData$zodSchema: z.ZodType<
  AnalyzeGoogleLogoDetectionResponseData
> = z.object({
  analysis: GoogleLogoDetectionAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeGoogleLogoDetectionResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeGoogleLogoDetectionResponseData | undefined;
};

export const AnalyzeGoogleLogoDetectionResponse$zodSchema: z.ZodType<
  AnalyzeGoogleLogoDetectionResponse
> = z.object({
  data: z.lazy(() => AnalyzeGoogleLogoDetectionResponseData$zodSchema)
    .optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
