/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a21fc8489316
 */

import * as z from "zod";
import {
  AnalyzeAIVisionModerationResponse,
  AnalyzeAIVisionModerationResponse$zodSchema,
} from "./analyzeaivisionmoderationresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeAiVisionModerationResponseResponse =
  | AnalyzeAIVisionModerationResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeAiVisionModerationResponseResponse$zodSchema: z.ZodType<
  AnalyzeAiVisionModerationResponseResponse
> = z.union([
  AnalyzeAIVisionModerationResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
