/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eedac4b61de0
 */

import * as z from "zod";
import {
  ImageQualityAnalysisData,
  ImageQualityAnalysisData$zodSchema,
} from "./imagequalityanalysisdata.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

export type AnalyzeImageQualityResponseData = {
  entity?: string | undefined;
  analysis?: ImageQualityAnalysisData | undefined;
};

export const AnalyzeImageQualityResponseData$zodSchema: z.ZodType<
  AnalyzeImageQualityResponseData
> = z.object({
  analysis: ImageQualityAnalysisData$zodSchema.optional(),
  entity: z.string().optional(),
});

export type AnalyzeImageQualityResponse = {
  limits?: LimitsObject | null | undefined;
  request_id?: string | undefined;
  data?: AnalyzeImageQualityResponseData | undefined;
};

export const AnalyzeImageQualityResponse$zodSchema: z.ZodType<
  AnalyzeImageQualityResponse
> = z.object({
  data: z.lazy(() => AnalyzeImageQualityResponseData$zodSchema).optional(),
  limits: LimitsObject$zodSchema.nullable().optional(),
  request_id: z.string().optional(),
});
