/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 91eaada8e42c
 */

import * as z from "zod";
import {
  AnalyzeAIVisionGeneralResponse,
  AnalyzeAIVisionGeneralResponse$zodSchema,
} from "./analyzeaivisiongeneralresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeAiVisionGeneralResponseResponse =
  | AnalyzeAIVisionGeneralResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeAiVisionGeneralResponseResponse$zodSchema: z.ZodType<
  AnalyzeAiVisionGeneralResponseResponse
> = z.union([
  AnalyzeAIVisionGeneralResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
