/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1fc62543b0bf
 */

import * as z from "zod";
import {
  AnalyzeHumanAnatomyResponse,
  AnalyzeHumanAnatomyResponse$zodSchema,
} from "./analyzehumananatomyresponse.js";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type AnalyzeHumanAnatomyResponseResponse =
  | AnalyzeHumanAnatomyResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const AnalyzeHumanAnatomyResponseResponse$zodSchema: z.ZodType<
  AnalyzeHumanAnatomyResponseResponse
> = z.union([
  AnalyzeHumanAnatomyResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
