/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 06cd99d33c6a
 */

import * as z from "zod";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";

export type AsyncOperationAcceptedResponseData = {
  task_id: string;
  status: TaskStatus;
};

export const AsyncOperationAcceptedResponseData$zodSchema: z.ZodType<
  AsyncOperationAcceptedResponseData
> = z.object({
  status: TaskStatus$zodSchema.describe("The status of an async task"),
  task_id: z.string(),
});

/**
 * Analysis accepted
 */
export type AsyncOperationAcceptedResponse = {
  data?: AsyncOperationAcceptedResponseData | undefined;
  request_id?: string | undefined;
};

export const AsyncOperationAcceptedResponse$zodSchema: z.ZodType<
  AsyncOperationAcceptedResponse
> = z.object({
  data: z.lazy(() => AsyncOperationAcceptedResponseData$zodSchema).optional(),
  request_id: z.string().optional(),
}).describe("Analysis accepted");
