/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3ca6beb71aac
 */

import * as z from "zod";

export type CaptioningAnalysisDataData = { caption: string };

export const CaptioningAnalysisDataData$zodSchema: z.ZodType<
  CaptioningAnalysisDataData
> = z.object({
  caption: z.string(),
});

export type CaptioningAnalysisData = {
  data: CaptioningAnalysisDataData;
  model_version?: number | undefined;
};

export const CaptioningAnalysisData$zodSchema: z.ZodType<
  CaptioningAnalysisData
> = z.object({
  data: z.lazy(() => CaptioningAnalysisDataData$zodSchema),
  model_version: z.int().optional(),
});
