/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 554344456559
 */

import * as z from "zod";

export type CldFashionAnalysisDataTags = {};

export const CldFashionAnalysisDataTags$zodSchema: z.ZodType<
  CldFashionAnalysisDataTags
> = z.object({});

export type CldFashionAnalysisData = {
  tags: CldFashionAnalysisDataTags;
  model_version?: number | undefined;
};

export const CldFashionAnalysisData$zodSchema: z.ZodType<
  CldFashionAnalysisData
> = z.object({
  model_version: z.int().optional(),
  tags: z.lazy(() => CldFashionAnalysisDataTags$zodSchema),
});
