/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 894ff33f3f83
 */

import * as z from "zod";

export type CldTextAnalysisDataTags = {};

export const CldTextAnalysisDataTags$zodSchema: z.ZodType<
  CldTextAnalysisDataTags
> = z.object({});

export type CldTextAnalysisData = {
  tags: CldTextAnalysisDataTags;
  model_version?: number | undefined;
};

export const CldTextAnalysisData$zodSchema: z.ZodType<CldTextAnalysisData> = z
  .object({
    model_version: z.int().optional(),
    tags: z.lazy(() => CldTextAnalysisDataTags$zodSchema),
  });
