/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 552cb1938fff
 */

import * as z from "zod";

export type CocoAnalysisDataTags = {};

export const CocoAnalysisDataTags$zodSchema: z.ZodType<CocoAnalysisDataTags> = z
  .object({});

export type CocoAnalysisData = {
  tags: CocoAnalysisDataTags;
  model_version?: number | undefined;
};

export const CocoAnalysisData$zodSchema: z.ZodType<CocoAnalysisData> = z.object(
  {
    model_version: z.int().optional(),
    tags: z.lazy(() => CocoAnalysisDataTags$zodSchema),
  },
);
