/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 54d020b54f48
 */

import * as z from "zod";
import { ErrorCategory, ErrorCategory$zodSchema } from "./errorcategory.js";

export type Details = {};

export const Details$zodSchema: z.ZodType<Details> = z.object({});

export type ErrorObject = {
  category?: ErrorCategory | undefined;
  code?: string | undefined;
  message?: string | undefined;
  details?: Details | undefined;
  request_id?: string | undefined;
};

export const ErrorObject$zodSchema: z.ZodType<ErrorObject> = z.object({
  category: ErrorCategory$zodSchema.optional(),
  code: z.string().optional(),
  details: z.lazy(() => Details$zodSchema).optional(),
  message: z.string().optional(),
  request_id: z.string().optional(),
});
