/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55a21b891851
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";

/**
 * Bad request
 */
export type ErrorResponse = { error?: ErrorObject | null | undefined };

export const ErrorResponse$zodSchema: z.ZodType<ErrorResponse> = z.object({
  error: ErrorObject$zodSchema.nullable().optional(),
}).describe("Bad request");
