/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 31d7acca0a1e
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const Feature = {
  GoogleTagging: "google_tagging",
  ObjectDetection: "object_detection",
  AiVision: "ai_vision",
} as const;
export type Feature = ClosedEnum<typeof Feature>;

export const Feature$zodSchema = z.enum([
  "google_tagging",
  "object_detection",
  "ai_vision",
]);
