/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 553bb8930632
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetTaskStatusResponse,
  GetTaskStatusResponse$zodSchema,
} from "./gettaskstatusresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type GetAnalysisTaskStatusRequest = { task_id: string };

export const GetAnalysisTaskStatusRequest$zodSchema: z.ZodType<
  GetAnalysisTaskStatusRequest
> = z.object({
  task_id: z.string().describe("The ID of the analysis task"),
});

export type GetAnalysisTaskStatusResponse =
  | GetTaskStatusResponse
  | ErrorResponse
  | RateLimitedResponse;

export const GetAnalysisTaskStatusResponse$zodSchema: z.ZodType<
  GetAnalysisTaskStatusResponse
> = z.union([
  GetTaskStatusResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
