/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b564d8b72b9a
 */

import * as z from "zod";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";

export type GetTaskStatusResponseData = {
  task_id?: string | undefined;
  status?: TaskStatus | undefined;
};

export const GetTaskStatusResponseData$zodSchema: z.ZodType<
  GetTaskStatusResponseData
> = z.object({
  status: TaskStatus$zodSchema.optional().describe(
    "The status of an async task",
  ),
  task_id: z.string().optional(),
});

export type GetTaskStatusResponse = {
  data?: GetTaskStatusResponseData | undefined;
  request_id?: string | undefined;
};

export const GetTaskStatusResponse$zodSchema: z.ZodType<GetTaskStatusResponse> =
  z.object({
    data: z.lazy(() => GetTaskStatusResponseData$zodSchema).optional(),
    request_id: z.string().optional(),
  });
