/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 918519fc41f1
 */

import * as z from "zod";

export type Vertex = { x?: number | undefined; y?: number | undefined };

export const Vertex$zodSchema: z.ZodType<Vertex> = z.object({
  x: z.int().optional(),
  y: z.int().optional(),
});

export type BoundingPoly = { vertices?: Array<Vertex> | undefined };

export const BoundingPoly$zodSchema: z.ZodType<BoundingPoly> = z.object({
  vertices: z.array(z.lazy(() => Vertex$zodSchema)).optional(),
});

export type LogoAnnotation = {
  mid?: string | undefined;
  description: string;
  score: number;
  bounding_poly: BoundingPoly;
};

export const LogoAnnotation$zodSchema: z.ZodType<LogoAnnotation> = z.object({
  bounding_poly: z.lazy(() => BoundingPoly$zodSchema),
  description: z.string(),
  mid: z.string().optional(),
  score: z.number(),
});

export type GoogleLogoDetectionAnalysisData = {
  logo_annotations: Array<LogoAnnotation>;
};

export const GoogleLogoDetectionAnalysisData$zodSchema: z.ZodType<
  GoogleLogoDetectionAnalysisData
> = z.object({
  logo_annotations: z.array(z.lazy(() => LogoAnnotation$zodSchema)),
});
