/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe5c21a7cf7f
 */

import * as z from "zod";

export type Label = { label: string; score: number };

export const Label$zodSchema: z.ZodType<Label> = z.object({
  label: z.string(),
  score: z.number(),
});

export type LabelAnnotations = { labels?: Array<Label> | undefined };

export const LabelAnnotations$zodSchema: z.ZodType<LabelAnnotations> = z.object(
  {
    labels: z.array(z.lazy(() => Label$zodSchema)).optional(),
  },
);

export type GoogleTaggingAnalysisData = { label_annotations: LabelAnnotations };

export const GoogleTaggingAnalysisData$zodSchema: z.ZodType<
  GoogleTaggingAnalysisData
> = z.object({
  label_annotations: z.lazy(() => LabelAnnotations$zodSchema),
});
