/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d8615836f31
 */

import * as z from "zod";

export type HumanAnatomyAnalysisDataTags = {};

export const HumanAnatomyAnalysisDataTags$zodSchema: z.ZodType<
  HumanAnatomyAnalysisDataTags
> = z.object({});

export type HumanAnatomyAnalysisData = {
  tags: HumanAnatomyAnalysisDataTags;
  model_version?: number | undefined;
};

export const HumanAnatomyAnalysisData$zodSchema: z.ZodType<
  HumanAnatomyAnalysisData
> = z.object({
  model_version: z.int().optional(),
  tags: z.lazy(() => HumanAnatomyAnalysisDataTags$zodSchema),
});
