/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 66d5b48b40c0
 */

import * as z from "zod";

export type ImageQualityAnalysisData = {
  quality?: string | undefined;
  score?: number | undefined;
  confidence?: number | undefined;
  model_version?: number | undefined;
};

export const ImageQualityAnalysisData$zodSchema: z.ZodType<
  ImageQualityAnalysisData
> = z.object({
  confidence: z.number().optional(),
  model_version: z.int().optional(),
  quality: z.string().optional(),
  score: z.number().optional(),
});
