/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2401b1ad1b38
 */

import * as z from "zod";
import { Feature, Feature$zodSchema } from "./feature.js";

export type Limit = {
  type: Feature;
  used_by_request?: number | null | undefined;
  remaining?: number | null | undefined;
  limit?: number | null | undefined;
  reset_time?: string | null | undefined;
};

export const Limit$zodSchema: z.ZodType<Limit> = z.object({
  limit: z.int().nullable().optional().describe("The total quota limit"),
  remaining: z.int().nullable().optional().describe("The remaining quota"),
  reset_time: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "Time in UTC when the limit will be reset",
  ),
  type: Feature$zodSchema,
  used_by_request: z.int().nullable().optional().describe(
    "The amount of quota used by the current request",
  ),
});

export type LimitsObject = { items?: Array<Limit> | undefined };

export const LimitsObject$zodSchema: z.ZodType<LimitsObject> = z.object({
  items: z.array(z.lazy(() => Limit$zodSchema)).optional(),
});
