/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e992e6df78f6
 */

import * as z from "zod";

export type LvisAnalysisDataTags = {};

export const LvisAnalysisDataTags$zodSchema: z.ZodType<LvisAnalysisDataTags> = z
  .object({});

export type LvisAnalysisData = {
  tags: LvisAnalysisDataTags;
  model_version?: number | undefined;
};

export const LvisAnalysisData$zodSchema: z.ZodType<LvisAnalysisData> = z.object(
  {
    model_version: z.int().optional(),
    tags: z.lazy(() => LvisAnalysisDataTags$zodSchema),
  },
);
