/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d632a065f0ef
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

/**
 * Rate limited
 */
export type RateLimitedResponse = {
  error?: ErrorObject | null | undefined;
  limits?: LimitsObject | null | undefined;
};

export const RateLimitedResponse$zodSchema: z.ZodType<RateLimitedResponse> = z
  .object({
    error: ErrorObject$zodSchema.nullable().optional(),
    limits: LimitsObject$zodSchema.nullable().optional(),
  }).describe("Rate limited");
