/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 77da6f3680a7
 */

import * as z from "zod";

export type ShopClassifierAnalysisDataTags = {};

export const ShopClassifierAnalysisDataTags$zodSchema: z.ZodType<
  ShopClassifierAnalysisDataTags
> = z.object({});

export type ShopClassifierAnalysisData = {
  tags: ShopClassifierAnalysisDataTags;
  model_version?: number | undefined;
};

export const ShopClassifierAnalysisData$zodSchema: z.ZodType<
  ShopClassifierAnalysisData
> = z.object({
  model_version: z.int().optional(),
  tags: z.lazy(() => ShopClassifierAnalysisDataTags$zodSchema),
});
