/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d297129752ea
 */

import * as z from "zod";

export type AssetId = { asset_id: string };

export const AssetId$zodSchema: z.ZodType<AssetId> = z.object({
  asset_id: z.string().describe("The asset ID to analyze"),
});

export type Uri = { uri: string };

export const Uri$zodSchema: z.ZodType<Uri> = z.object({
  uri: z.string().describe("The URI of the asset to analyze"),
});

export type Source = Uri | AssetId;

export const Source$zodSchema: z.ZodType<Source> = z.union([
  z.lazy(() => Uri$zodSchema),
  z.lazy(() => AssetId$zodSchema),
]);
