/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1286169d34b5
 */

import * as z from "zod";

export type UnidetAnalysisDataTags = {};

export const UnidetAnalysisDataTags$zodSchema: z.ZodType<
  UnidetAnalysisDataTags
> = z.object({});

export type UnidetAnalysisData = {
  tags: UnidetAnalysisDataTags;
  model_version?: number | undefined;
};

export const UnidetAnalysisData$zodSchema: z.ZodType<UnidetAnalysisData> = z
  .object({
    model_version: z.int().optional(),
    tags: z.lazy(() => UnidetAnalysisDataTags$zodSchema),
  });
