/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e70cb91f63e
 */

import * as z from "zod";

export type Detection = { name: string; confidence: number };

export const Detection$zodSchema: z.ZodType<Detection> = z.object({
  confidence: z.number(),
  name: z.string(),
});

export type WatermarkDetectionAnalysisData = {
  detections?: Array<Detection> | undefined;
  model_version?: number | undefined;
};

export const WatermarkDetectionAnalysisData$zodSchema: z.ZodType<
  WatermarkDetectionAnalysisData
> = z.object({
  detections: z.array(z.lazy(() => Detection$zodSchema)).optional(),
  model_version: z.int().optional(),
});
